### ISSUE TITLE
SQL-injection

### ISSUE THREAD

**Issue by wellenc-lex** [ParfenovVladislav/AviaTickets#5]
Привет, искал приложения под авиабилеты, наткнулся на ваш проект и решил посмотреть исходники.

Обнаружил, что у вас данные пользователя обрабатываются не полностью ( пример - https://github.com/ParfenovVladislav/AviaTickets/blob/master/AviaTickets/register.php , параметр - $name ),
stripslashes и htmlspecialchars не защитят от SQL-inj, для этого нужно дополнительно параметр обрабатывать mysql_real_escape_string

Всего хорошего, с уважением, Алексей.

**Comment by ParfenovVladislav** [comment]
Привет, Алексей, спасибо большое за отзыв!
Обязательно учтем.
